#ifndef COMUN_H_INCLUDED
#define COMUN_H_INCLUDED

#define TODO_OK 0
#define PERDIDA_DE_DATOS -7
#define JUGADOR_NO_CARGADO -6
#define CHAR_NO_ENCONTRADO -5
#define SIN_MEM -5
#define ERROR_ARCHIVO -4
#define ERROR_SOBRECARGA_CARTAS -3
#define ERROR_OBTENER_TIPOPODER_SEGUN_CARTA -2

#endif // COMUN_H_INCLUDED
